Add pid support
NeatTeam1943/2023-Robot pull request #38
Opened 2023-02-09 16:41 UTC by ofirlang

2023-02-11 16:55 UTC, guy-av requested changes

2023-02-11 16:55 UTC, guy-av commented on src/main/java/frc/robot/subsystems/DriveTrain.java
> +import java.beans.Encoder;
Wrong import

2023-02-11 16:55 UTC, guy-av commented on src/main/java/frc/robot/subsystems/DriveTrain.java
> +  private final SimpleMotorFeedforward m_DriveTrainFeedforward;
```suggestion
  private final SimpleMotorFeedforward m_driveTrainFeedforward;
```

2023-02-11 16:55 UTC, guy-av commented on src/main/java/frc/robot/subsystems/DriveTrain.java
> +    return m_leftFront.getSelectedSensorPosition();
Should return the average measure distance by all the encoders. This method was already added by @VenusM3, `getDistance()`

2023-02-11 16:55 UTC, guy-av commented on src/main/java/frc/robot/subsystems/DriveTrain.java
> +    m_leftMotors.setVoltage(output + m_DriveTrainFeedforward.calculate(setpoint));
Set the output only to left motors? What about the right ones?
Setting only one side will send the robot spinning uncontrollably

2023-02-11 16:55 UTC, guy-av commented on src/main/java/frc/robot/Constants.java
> +    public static final double kDistanceToTarget = 0.0;
Your distance to target is usually not a constant, it's value that changes as the game progresses.

2023-02-11 16:55 UTC, guy-av commented on src/main/java/frc/robot/subsystems/DriveTrain.java
> +    setSetpoint(DriveTrainConstants.kDistanceToTarget);
Do not set a SetPoint inside the constructor, your SetPoint changes according to where you are on the field it's not constant.

For example, if I stand near the feeder, I will need to drive a whole lot more to the charge station than I would need if I were to stand near the grid.

2023-02-14 21:22 UTC, neatteamsoftware requested changes

2023-02-14 21:22 UTC, neatteamsoftware commented on src/main/java/frc/robot/Constants.java
> +    public static final double kInitialSetPoint = 0.0;
delete this

2023-02-14 21:22 UTC, neatteamsoftware commented on src/main/java/frc/robot/Constants.java
> +    public static final double kInitialSetPoint = 0.0;
add tolerance instead

2023-02-14 21:22 UTC, neatteamsoftware commented on src/main/java/frc/robot/subsystems/DriveTrain.java
> +    getController().setTolerance(DriveTrainConstants.kInitialSetPoint);
use actual tolerance

2023-02-14 21:22 UTC, neatteamsoftware commented on src/main/java/frc/robot/subsystems/DriveTrain.java
> +    setSetpoint(DriveTrainConstants.kInitialSetPoint - getMeasurement());
Remove this line, you do not want to change the setpoint every 20ms... You want it to be set by the autonomous command that will run.

2023-02-14 22:58 UTC, neatteamsoftware approved these changes

2023-02-14 22:59 UTC, guy-av approved these changes

2023-02-14 23:00 UTC, merged